// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Landmark struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Description string `json:"description"`
	Address     string `json:"address"`
	State       string `json:"state"`
	User        *User  `json:"user"`
}

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type NewLandmark struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Address     string  `json:"address"`
	State       string  `json:"state"`
	UserID      string  `json:"userID"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type User struct {
	ID        string      `json:"id"`
	Name      string      `json:"name"`
	Landmarks []*Landmark `json:"landmarks"`
}
